server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shual_db?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 741258963
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
prefix:
  url: https://127.0.0.1